---
services:
  db-central:
    image: postgresql17
      #container_name: db-central
    ports:
      - "5432:5432/tcp"
    volumes:
      - /var/central-telefonica/var/lib/pgsql/data:/var/lib/pgsql/data
    networks:
      ast:
        ipv4_address: 10.89.1.3
    restart: unless-stopped

  central:
    image: asterisk20-rocky:new
      #container_name: central
    ports:
      - "5060:5060/udp"
      - "80:80/tcp"
      - "10000-10200:10000-10200/udp"
      - "8088-8089:8088-8089/tcp"
      - "9543:9543/tcp"
    volumes:
      - /var/central-telefonica/var/spool/asterisk:/var/spool/asterisk
      - /var/central-telefonica/var/log/asterisk:/var/log/asterisk
      - /var/central-telefonica/var/cache/asterisk:/var/cache/asterisk
      - /var/central-telefonica/etc/asterisk:/etc/asterisk
      - /var/central-telefonica/var/lib/asterisk:/var/lib/asterisk
    networks:
      ast:
        ipv4_address: 10.89.1.2
    restart: unless-stopped
    depends_on:
      - db-central

networks:
  ast:
    driver: bridge
    ipam:
      config:
        - subnet: "10.89.1.0/24"
