---
version: '3.8'

services:
  central:
    image: asterisk20-rocky:1.0.0
    container_name: central
    ports:
      - "5060:5060/udp"
      - "10000-20000:10000-20000/udp"
      - "8088-8089:8088-8089/tcp"
      - "9547:9547/tcp"
    volumes:
      - /var/central-telefonica/var/spool/asterisk:/var/spool/asterisk
      - /var/central-telefonica/var/log/asterisk:/var/log/asterisk
      - /var/central-telefonica/var/cache/asterisk:/var/cache/asterisk
      - /var/central-telefonica/etc/asterisk:/etc/asterisk
      - /var/central-telefonica/var/lib/asterisk:/var/lib/asterisk
    networks:
      ast:
        ipv4_address: 10.89.1.2
    restart: unless-stopped

  db-central:
    image: postgresql17:1.0.0
    container_name: db-central
    ports:
      - "5432:5432/tcp"
    volumes:
      - /var/central-telefonica/var/lib/pgsql/data:/var/lib/pgsql/data
    networks:
      ast:
        ipv4_address: 10.89.1.3
    restart: unless-stopped

networks:
  ast:
    driver: bridge
    ipam:
      config:
        - subnet: "10.89.1.0/24"

