---
version: '3'

services:
  asterisk:
    image: asterisk20-rocky:1.0.0
    container_name: central
    networks:
      ast:
        ipv4_address: 10.89.1.2
    ports:
      - "5060:5060/udp"
      - "10000-20000:10000-20000/udp"
      - "8089:8089/tcp"
      - "8088:8088/tcp"
    volumes:
      - gravacoes:/var/spool/asterisk
      - asterisk-log:/var/log/asterisk
      - cache-asterisk:/var/cache/asterisk
      - asterisk-config:/etc/asterisk
      - var-config-asterisk:/var/lib/asterisk
    networks:
      - ast

  db-central:
    image: postgresql17:1.0.0
    container_name: db-central
    networks:
      ast:
        ipv4_address: 10.89.1.3
    volumes:
      - config-db:/var/lib/pgsql/data
    networks:
      - ast

networks:
  ast:
    driver: bridge
    ipam:
      config:
        - subnet: "10.89.1.0/24"

volumes:
  gravacoes:
  asterisk-log:
  cache-asterisk:
  asterisk-config:
  var-config-asterisk:
  config-db:

